load: data/fid_3_5_22.o2
output_format: CSV
select_model: 470 738 0.5 13.0 62.4 32.8 0.9
set:
  a_virial: 10.0
  b_virial: 10.0
  extend_frdm: false
  fd_A_max: 600
  fixed_dist_alg: 1999
  function_verbose: 0
  max_ratio: 7.0
