FROM awsteiner/o2scl:v0.929a2_u23.04_py
MAINTAINER Andrew W. Steiner (awsteiner0@protonmail.com)

# --------------------------------------------------------------------------
# Additional packages

RUN apt install libopenmpi-dev

# --------------------------------------------------------------------------
# UTK EOS

# Set makefile variables
ENV CXX g++
ENV MPI_CXX mpicxx
ENV CFLAGS -I/usr/lib/x86_64-linux-gnu/openmpi/include/ \
  -I/usr/include/python3.11 \
  -I/usr/local/lib/python3.11/dist-packages/numpy/core/include \
  -I/usr/include/hdf5/serial -std=c++14 -DO2SCL_NO_BOOST_MULTIPRECISION
ENV LDFLAGS -L/usr/lib/x86_64-linux-gnu/hdf5/serial \
  -L/usr/lib/x86_64-linux-gnu -lpython3.11

WORKDIR /opt
RUN git clone https://github.com/awsteiner/eos 
WORKDIR /opt/eos
RUN git checkout 00058579
RUN make eos_nuclei eos

# --------------------------------------------------------------------------
# Make sure it runs

RUN mpirun --allow-run-as-root -np 1 ./eos -help
RUN mpirun --allow-run-as-root -np 1 ./eos_nuclei -help








