openapi: 3.0.0

info:
  version: 1.0.0
  title: E4MMA-EOS module
  contact:
    email: sroy14@vols.utk.edu
  description: "Readme.md"

servers:
    - url: "/"
      description: "Dummy server"

paths:
  /input/config.yaml:
    put:
      summary: Input parameters for e4mma module
      description: >
          possible arguments to take for e4mma module
      operationId: putInputParams
      security: []
      requestBody:
        description: Input parameters
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/config'
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid input provided

  /input/fid_3_5_22.o2:
    put:
      summary: Fiducial table for e4mma module
      description: >
          Fiducial table for e4mma module
      operationId: getEoS
      security: []
      requestBody:
        description: EOS table
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/table'
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid input provided

  /output/status.yaml:
    get:
      summary: Status Crust DFT EoS module execution
      description: >
          Describes the current status of the Crust DFT 
          EoS module during execution. This includes warning, 
          error and success messages.
      operationId: getStatus
      security: []
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/status'
        '500':
          description: Run time error in calculation

  /output/e4mma_w_Lepton.csv:
    get:
      summary: Equation of state with Lepton
      description: >
        fill
      operationId: getEoSwLepton
      security: []
      responses:
        '200':
          description: Successful operation
          content:
            csv:
              schema:
                $ref: '#/components/schemas/e4mma_wo_lepton'
            hdf5:
              schema:
                $ref: '#/components/schemas/e4mma_wo_lepton'
        '500':
          description: Run time error in calculation

  /output/e4mma_wo_Lepton.csv:
    get:
      summary: Equation of state without Lepton
      description: >
        fill
      operationId: getEoSwoLepton
      security: []
      responses:
        '200':
          description: Successful operation
          content:
            csv:
              schema:
                $ref: '#/components/schemas/e4mma_wo_lepton'
            hdf5:
              schema:
                $ref: '#/components/schemas/e4mma_wo_lepton'
        '500':
          description: Run time error in calculation

components:
  schemas:
    table:
      title: Fiducial table for Crust DFT module
      description: Fiducial table for Crust DFT module
      type: object
      required: [input_table]
      properties:
        input_table:
          default: "fid_3_5_22.o2"
          description: Loads an EOS table in to memory. In the case where MPI is used, only one MPI
            rank reads the table at a time.
          title: Load an EOS table.
          type: string
    config:
      title: Input parameters
      description: Input parameters for e4mma eos
      type: object
      required: [load]
      properties:
        load:
          default: "fid_3_5_22.o2"
          description: Loads an EOS table in to memory. In the case where MPI is used, only one MPI
            rank reads the table at a time.
          title: Load an EOS table.
          type: string
        output_format:
          default: "CSV"
          description: "Format of the output files for Lepton module"
          type: string
          title: output format
        set:
          type: object
          description: This command sets the value of a parameter. A list of parameters can be
            obtained by e.g. -help set on the command-line or "help set " in interactive
            mode.For floating point or integer parameters, constant expressions can be
            used, e.g. acos(-1). For string-like parameters, quotes can be used to specify
            parameters which have single spaces. All whitespace is compressed into a
            single space. Quotes inside a word with no whitespace are ignored.
          title: Set the value of a parameter.
          properties:  
                nB_grid_spec:
                  type: string
                  description: The function for default baryon density grid. 'N,func(i)', 
                    i takes values from 0-N 
                    and func(i) fills up the grid . The user can change the grid length N and the 
                    desired function.
                  default: '301,10^(i*0.04-12)*2.0'   
                Ye_grid_spec:
                  type: string
                  description: The function for default electron fraction grid. 'N,func(i)', 
                    i takes values from 0-N 
                    and func(i) fills up the grid. The user can change the grid length N and the 
                    desired function.
                  default: '70,0.01*(i+1)'
                verbose:
                  type: integer
                  description: Verbose parameter.
                  default: 0
                inc_lepton:
                  type: boolean
                  description: If true, include leptons.
                  default: false
        
    status:
      title: Module Status
      description: Status of module execution including a code and optionally a message
      type: object
      required:
        - code
      properties:
        message:
          type: string
          default: ""
        code:
          type: integer
          enum: [200, 400, 500]
          description: >
            Status code:
             * `200` - Success/OK
             * `400` - Bad request/client error
             * `500` - Internal error
          default: 200
    
    e4mma_wo_lepton:
      title: e4mma output for Lepton
      description: Output of e4mma for Lepton module
      type: array
      items:
        type: object
        properties:
          temperature:
            description: Temperature
            type: number
            x-unit: MeV
          mu_B:
            description: Baryon chemical potential
            type: number
            x-unit: MeV
          mu_S:
            description: Strange chemical potential
            type: number
            x-unit: MeV
          mu_Q:
            description: Charge chemical potential
            type: number
            x-unit: MeV
          baryon_density:
            description: Baryon density
            type: number
            x-unit: 1/fm3
          total_strangeness_density:
            description: Total strangeness density
            type: number
            x-unit: 1/fm3
          total_charge_density:
            description: Total charge density
            type: number
            x-unit: 1/fm3 
          energy_density:
            description: Energy density
            type: number
            x-unit: MeV/fm3
          pressure:
            description: Pressure
            type: number
            x-unit: MeV/fm3
          entropy_density:
            description: Entropy density
            type: number
            x-unit: 1/fm3


