openapi: 3.0.0
components:
  schemas:
    Status:
      title: Status
      description: Status of module execution including a code and optionally a message
      type: object
      required:
        - code
      properties:
        message:
          type: string
          default: ""
        code:
          type: integer
          enum: [200, 400, 500]
          description: >
            Status code:
             * `200` - Success/OK
             * `400` - Bad request/client error
             * `500` - Internal error
          default: 200
