name: CI/CD Pipeline

on:
  push:
    branches:
      - muses  
  pull_request:
    branches:
      - muses  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t crust_dft:latest .

      - name: Run tests
        run: |
          docker run --rm crust_dft:latest sh -c \
          "curl -o fid_3_5_22.o2 https://isospin.roam.utk.edu/public_data/eos_tables/du21/fid_3_5_22.o2 && mpirun --allow-run-as-root -np 1 ./eos_nuclei -load fid_3_5_22.o2 -point-nuclei 0.16 0.4 1.0"


      - name: Push Docker image
        run: |
          docker push crust_dft:latest
