name: CI/CD Pipeline

on:
  schedule:
    - cron: '32 9 * * *'  # Runs daily at 9:32 AM UTC
  push:
    branches:
      - "muses"
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - "muses"

env:
  REGISTRY: docker.io
  IMAGE_NAME: nostrad1/utk-eos
  IMAGE_TAG: v1.9.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: |
            /tmp/.buildx-cache
          key: ${{ runner.os }}-docker-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-docker-

      - name: Build Docker image
        run: |
          mkdir -p /tmp/.buildx-cache
          docker buildx create --use
          docker buildx build --cache-to=type=local,dest=/tmp/.buildx-cache --cache-from=type=local,src=/tmp/.buildx-cache -t $REGISTRY/$IMAGE_NAME:$IMAGE_TAG .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Test Docker image
        run: |
          sudo docker run $REGISTRY/$IMAGE_NAME:$IMAGE_TAG sh -c "bash test.sh"

  push:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Log in to Docker Hub
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Push Docker image
        run: |
          sudo docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG
