name: CI/CD Pipeline

on:
  schedule:
    - cron: '32 9 * * *' 
  push:
    branches:
      - "muses"
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - "muses"

env:
  REGISTRY: docker.io
  IMAGE_NAME: nostrad1/utk-eos
  IMAGE_TAG: v1.9.1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          sudo docker build -t $REGISTRY/$IMAGE_NAME:$IMAGE_TAG .

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v4

      - name: Test Docker image
        run: |
          sudo docker run $REGISTRY/$IMAGE_NAME:$IMAGE_TAG sh -c "bash test.sh"

  push:
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Log in to Docker Hub
        run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      - name: Push Docker image
        run: |
          sudo docker push $REGISTRY/$IMAGE_NAME:$IMAGE_TAG
